version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgresql_development
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root_sql
      - POSTGRES_USER=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
