version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_sql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
