CREATE USER 'admin'@'%' IDENTIFIED BY 'admin1234';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE bdt;

CREATE TABLE `bdt`.`BT_TM_USUARIO` (
  `ID_USUARIO` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_NOMBRE` VARCHAR(100),
  `AP_APELLIDO_PATERNO` VARCHAR(100),
  `AP_APELLIDO_MATERNO` VARCHAR(100),
  `URL_IMAGEN` VARCHAR(100),
  `USUARIO` VARCHAR(100),
  `PASSWORD` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TM_ROL` (
  `ID_ROL` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_ROL` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TX_ROL_USUARIO` (
  `ID_ROL_USUARIO` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_USUARIO` INT,
  `ID_ROL` INT
);

CREATE TABLE `bdt`.`BT_TM_TALENTO` (
  `ID_TALENTO` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_NOMBRE` VARCHAR(100),
  `AP_APELLIDO_PATERNO` VARCHAR(100),
  `AP_APELLIDO_MATERNO` VARCHAR(100),
  `URL_IMAGEN` VARCHAR(100),
  `DE_DESCRIPCION` VARCHAR(100),
  `ID_PERFIL_TALENTO` INT,
  `ID_TIPO_MONEDA` INT,
  `NU_MONTO_INICIAL` INT,
  `NU_MONTO_FINAL` INT,
  `NU_CELULAR` VARCHAR(100),
  `URL_LINKDN` VARCHAR(100),
  `URL_GITHUB` VARCHAR(100),
  `ID_PAIS` INT,
  `ID_CIUDAD` INT,
  `FE_CREACION` DATE
);

CREATE TABLE `bdt`.`BT_TD_ARCHIVO` (
  `ID_ARCHIVO` INT AUTO_INCREMENT PRIMARY KEY,
  `FL_TIPO_ARCHIVO` INT,
  `URL_ARCHIVO` VARCHAR(100),
  `ID_TALENTO` INT
);

CREATE TABLE `bdt`.`BT_TD_PERFIL_TALENTO` (
  `ID_PERFIL_TALENTO` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_PERFIL_TALENTO` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TD_TIPO_MONEDA` (
  `ID_TIPO_MONEDA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_TIPO_MONEDA` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TD_CIUDAD` (
  `ID_CIUDAD` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_CIUDAD` VARCHAR(100),
  `ID_PAIS` INT
);

CREATE TABLE `bdt`.`BT_TD_PAIS` (
  `ID_PAIS` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_PAIS` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TM_LISTA_USUARIO` (
  `ID_LISTA_USUARIO` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_USUARIO` INT,
  `NO_LISTA_USUARIO` VARCHAR(100),
  `FE_CREACION` DATE
);

CREATE TABLE `bdt`.`BT_TX_LISTA_USUARIO_TALENTO` (
  `ID_LISTA_USUARIO_DETALLE` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_LISTA_USUARIO` INT,
  `ID_TALENTO` INT
);

CREATE TABLE `bdt`.`BT_TD_EXPERIENCIA_LABORAL` (
  `ID_EXPERIENCIA_LABORAL` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_EXPERIENCIA_LABORAL` VARCHAR(100),
  `NO_PUESTO` VARCHAR(100),
  `FE_INICIO` DATE,
  `FE_FIN` DATE,
  `ID_TALENTO` INT
);

CREATE TABLE `bdt`.`BT_TD_EXPERIENCIA_EDUCATIVA` (
  `ID_EXPERIENCIA_EDUCATIVA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_INSTITUCION_EDUCATIVA` VARCHAR(100),
  `NO_CARRERA` VARCHAR(100),
  `NO_GRADO` VARCHAR(100),
  `FE_INICIO` DATE,
  `FE_FIN` DATE,
  `ID_TALENTO` INT
);

CREATE TABLE `bdt`.`BT_TM_IDIOMA` (
  `ID_IDIOMA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_IDIOMA` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TD_NIVEL_IDIOMA` (
  `ID_NIVEL_IDIOMA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_NIVEL` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TX_IDIOMA_TALENTO` (
  `ID_IDIOMA_TALENTO` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_IDIOMA` INT,
  `ID_NIVEL` INT,
  `ID_TALENTO` INT
);

CREATE TABLE `bdt`.`BT_TD_FEEDBACK_TALENTO` (
  `ID_FEEDBACK` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_TALENTO` INT,
  `NU_ESTRELLAS` INT,
  `DE_DESCRIPCION` VARCHAR(100)
);

CREATE TABLE `bdt`.`BT_TD_HABILIDAD_TECNICA` (
  `ID_HABILIDAD_TECNICA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_HABILIDAD` VARCHAR(100),
  `ID_TALENTO` INT,
  `ID_NIVEL_HABILIDAD_TECNICA` INT,
  `NU_ANIOS` INT
);

CREATE TABLE `bdt`.`BT_TD_HABILIDAD_BLANDA` (
  `ID_HABILIDAD_BLANDA` INT AUTO_INCREMENT PRIMARY KEY,
  `NO_HABILIDAD` VARCHAR(100),
  `ID_TALENTO` INT
);

ALTER TABLE `bdt`.`BT_TX_ROL_USUARIO` ADD FOREIGN KEY (`ID_USUARIO`) REFERENCES `bdt`.`BT_TM_USUARIO` (`ID_USUARIO`);

ALTER TABLE `bdt`.`BT_TX_ROL_USUARIO` ADD FOREIGN KEY (`ID_ROL`) REFERENCES `bdt`.`BT_TM_ROL` (`ID_ROL`);

ALTER TABLE `bdt`.`BT_TD_ARCHIVO` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TM_TALENTO` ADD FOREIGN KEY (`ID_PERFIL_TALENTO`) REFERENCES `bdt`.`BT_TD_PERFIL_TALENTO` (`ID_PERFIL_TALENTO`);

ALTER TABLE `bdt`.`BT_TM_TALENTO` ADD FOREIGN KEY (`ID_TIPO_MONEDA`) REFERENCES `bdt`.`BT_TD_TIPO_MONEDA` (`ID_TIPO_MONEDA`);

ALTER TABLE `bdt`.`BT_TD_CIUDAD` ADD FOREIGN KEY (`ID_PAIS`) REFERENCES `bdt`.`BT_TD_PAIS` (`ID_PAIS`);

ALTER TABLE `bdt`.`BT_TM_TALENTO` ADD FOREIGN KEY (`ID_PAIS`) REFERENCES `bdt`.`BT_TD_PAIS` (`ID_PAIS`);

ALTER TABLE `bdt`.`BT_TM_TALENTO` ADD FOREIGN KEY (`ID_CIUDAD`) REFERENCES `bdt`.`BT_TD_CIUDAD` (`ID_CIUDAD`);

ALTER TABLE `bdt`.`BT_TM_LISTA_USUARIO` ADD FOREIGN KEY (`ID_USUARIO`) REFERENCES `bdt`.`BT_TM_USUARIO` (`ID_USUARIO`);

ALTER TABLE `bdt`.`BT_TX_LISTA_USUARIO_TALENTO` ADD FOREIGN KEY (`ID_LISTA_USUARIO`) REFERENCES `bdt`.`BT_TM_LISTA_USUARIO` (`ID_LISTA_USUARIO`);

ALTER TABLE `bdt`.`BT_TX_LISTA_USUARIO_TALENTO` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TD_EXPERIENCIA_LABORAL` ADD FOREIGN KEY (`ID_EXPERIENCIA_LABORAL`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TD_EXPERIENCIA_EDUCATIVA` ADD FOREIGN KEY (`ID_EXPERIENCIA_EDUCATIVA`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TX_IDIOMA_TALENTO` ADD FOREIGN KEY (`ID_IDIOMA`) REFERENCES `bdt`.`BT_TM_IDIOMA` (`ID_IDIOMA`);

ALTER TABLE `bdt`.`BT_TX_IDIOMA_TALENTO` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TX_IDIOMA_TALENTO` ADD FOREIGN KEY (`ID_NIVEL`) REFERENCES `bdt`.`BT_TD_NIVEL_IDIOMA` (`ID_NIVEL_IDIOMA`);

ALTER TABLE `bdt`.`BT_TD_FEEDBACK_TALENTO` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TD_HABILIDAD_TECNICA` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);

ALTER TABLE `bdt`.`BT_TD_HABILIDAD_BLANDA` ADD FOREIGN KEY (`ID_TALENTO`) REFERENCES `bdt`.`BT_TM_TALENTO` (`ID_TALENTO`);


INSERT INTO bdt.BT_TM_IDIOMA (ID_IDIOMA,NO_IDIOMA) VALUES (1,'ESPAÑOL');
INSERT INTO bdt.BT_TM_IDIOMA (ID_IDIOMA,NO_IDIOMA) VALUES (2,'INGLES');
INSERT INTO bdt.BT_TM_IDIOMA (ID_IDIOMA,NO_IDIOMA) VALUES (3,'FRANCES');

INSERT INTO bdt.BT_TD_NIVEL_IDIOMA (ID_NIVEL_IDIOMA,NO_NIVEL) VALUES (1,'BASICO');
INSERT INTO bdt.BT_TD_NIVEL_IDIOMA (ID_NIVEL_IDIOMA,NO_NIVEL) VALUES (2,'INTERMEDIO');
INSERT INTO bdt.BT_TD_NIVEL_IDIOMA (ID_NIVEL_IDIOMA,NO_NIVEL) VALUES (3,'AVANZADO');
INSERT INTO bdt.BT_TD_NIVEL_IDIOMA (ID_NIVEL_IDIOMA,NO_NIVEL) VALUES (4,'NATIVO');


INSERT INTO bdt.BT_TD_TIPO_MONEDA (ID_TIPO_MONEDA,NO_TIPO_MONEDA) VALUES (1,'SOL');
INSERT INTO bdt.BT_TD_TIPO_MONEDA (ID_TIPO_MONEDA,NO_TIPO_MONEDA) VALUES (2,'DOLAR');

INSERT INTO bdt.BT_TD_PERFIL_TALENTO (ID_PERFIL_TALENTO,NO_PERFIL_TALENTO) VALUES (1,'BACKEND DEVELOPER');
INSERT INTO bdt.BT_TD_PERFIL_TALENTO (ID_PERFIL_TALENTO,NO_PERFIL_TALENTO) VALUES (2,'FRONTEND DEVELOPER');
INSERT INTO bdt.BT_TD_PERFIL_TALENTO (ID_PERFIL_TALENTO,NO_PERFIL_TALENTO) VALUES (3,'FULLSTACK DEVELOPER');
INSERT INTO bdt.BT_TD_PERFIL_TALENTO (ID_PERFIL_TALENTO,NO_PERFIL_TALENTO) VALUES (4,'ANALISTA QA');

INSERT INTO bdt.BT_TM_ROL (ID_ROL,NO_ROL) VALUES (1,'VISITANTE');
INSERT INTO bdt.BT_TM_ROL (ID_ROL,NO_ROL) VALUES (2,'RECLUTADOR');

INSERT INTO bdt.BT_TD_PAIS (ID_PAIS,NO_PAIS) VALUES (1,'PERU');
INSERT INTO bdt.BT_TD_PAIS (ID_PAIS,NO_PAIS) VALUES (2,'BOLIVIA');

INSERT INTO bdt.BT_TD_CIUDAD (ID_CIUDAD,NO_CIUDAD,ID_PAIS) VALUES (1,'LIMA',1);
INSERT INTO bdt.BT_TD_CIUDAD (ID_CIUDAD,NO_CIUDAD,ID_PAIS) VALUES (2,'AREQUIPA',1);
INSERT INTO bdt.BT_TD_CIUDAD (ID_CIUDAD,NO_CIUDAD,ID_PAIS) VALUES (3,'LA PAZ',2);